version: '3.7'

services:
#   postgres:
#     image: postgres:14-alpine
#     environment:
#        - POSTGRES_USER=keycloak
#        - POSTGRES_PASSWORD=abc
#        - POSTGRES_DB=keycloak
   keycloak:
     image: quay.io/keycloak/keycloak:21.1
     command: start-dev
     environment:
        - KC_HOSTNAME=2.test.jorisgutjahr.eu
        - KC_PROXY=edge
        - KC_FEATURES=declarative-user-profile
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=password
     volumes:
        - keycloak-data:/opt/keycloak
     ports:
      - 8080:8080

volumes:
  keycloak-data:
